---
all:
  children:
    aws:
      children:
        signaling:
          hosts:
            aws-signaling:
              ansible_host: 44.193.172.237
              private_ip: 10.2.0.10
              
        media:
          hosts:
            aws-media:
              ansible_host: 13.216.104.26
              private_ip: 10.2.0.20
      
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/multi-cloud-voip-lab/.ssh/multi-cloud-key
        ansible_python_interpreter: /usr/bin/python3
        cloud_provider: aws
        region: us-east-1
